---
language: c

env:
  - IMAGE_NAME=precurse/security-tools

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - docker build -t $IMAGE_NAME .

script:
  - docker run --entrypoint nmap -it $IMAGE_NAME --version
  - docker run --entrypoint wpscan -it $IMAGE_NAME --version
  - docker run --entrypoint gobuster -it $IMAGE_NAME -h
  - docker run --entrypoint binwalk -it $IMAGE_NAME /bin/bash
  - docker run --entrypoint john -it $IMAGE_NAME
  - docker run --entrypoint cewl -it $IMAGE_NAME --help
  - docker run --entrypoint ffuf -it $IMAGE_NAME -V
  - docker run --entrypoint ncrack -it $IMAGE_NAME --version
